AdvancedPhotonSource/tike

tike/ptycho.py
We must normalize the conjugate of the probe function such that
the max intensity of probes can be greater than 1. Otherwise,
the tike.ptycho will not converge.
=> BUG: Normalize probe conjugate for probes with intensity > 1

tike/ptycho.py
We previously replaced numpy angle with a cheaper alternative
but because of zero division it did not behave the same as
np.angle. This patch makes the trig identity behave the same way
as numpy angle when the complex number is zero. nan and inf were
not considered in this patch.
=> BUG: Prevent zero division in np.angle replacement

MANIFEST.in, meta.yaml, setup.cfg
Adding the where param makes nosetest called from the root directory execute in the correct place, and updated manifest removes build junk from install.
=> BLD: Update Manifest and nosetests config

azure-pipelines.yml, src/tike/view.py
Adds a warning to a plotting function that when the amplitude of a complex number is zero, then the phase will not be recovered correctly. This will cause the images to look discontinuous because zero amplitudes will render as having phase of PI or zero.
=> DOC: Add warning to plot_phase about zero-amplitudes

tests/operators/test_convolution.py, tests/operators/test_propagation.py, tests/operators/test_ptycho.py, tests/operators/util.py
This basically fixes some broken (deactivated tests) where the imaginary part of the adjoint tests was wrong because I wasn't using the correct order of the arguments for the inner product.
=> TST: Fix imaginary part of adjoint operator tests

src/tike/operators/ptycho.py
When composing a context manager from other context managers
we must also call __enter__ for the composed classes.
=> BUG: Must call __enter__ for composed classes

src/.clang-format, src/tike/operators/cupy/convolution.cu
This is just one commit to add a clang-format file to the repository so that CUDA kernels are formatted consistently.
=> STY: Add clang-format and format .cu files

meta.yaml, tests/operators/test_lamino.py, tests/test_communicator.py, tests/test_tomo.py
Because:
- It's easier to remember to do when writing tests than having
to go into another CI file to disable tests
=> TST: Use pytest.skip() instead of manually selecting files

src/tike/operators/cupy/convolution.cu, src/tike/operators/cupy/convolution.py, src/tike/operators/cupy/propagation.py, src/tike/operators/numpy/convolution.py, src/tike/operators/numpy/propagation.py, src/tike/operators/numpy/ptycho.py, src/tike/ptycho/ptycho.py
Currently, if the number of scan positions is not a multiple of the number of GPUs, we must keep track of two Ptycho operators. There are three solutions to this problem:
1. Keep `nscan`; track multiple Ptycho operators. I think this is not a good option.
2. Remove the `nscan` parameter from the Ptycho operator. It will simplify the implementation of multi-GPU workloads by letting multiple-GPUs share the same Ptycho operator. @xiaodong-yu  suggested this solution.
3. Keep `nscan`; restrict or pad the number of scan positions so that it is always multiple of the number of GPUs.
This PR takes the second approach. The `nscan` parameter has been purged from the operators. It is no longer used when passed as an argument in the constructors. Instead, this parameter is pulled from the shape of …
=> Remove nscan param to prepare for multi-GPU

src/tike/operators/cupy/convolution.py, src/tike/operators/cupy/operator.py, src/tike/operators/cupy/ptycho.py, src/tike/operators/numpy/operator.py, src/tike/opt.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/combined.py, tests/test_communicator.py, tests/test_ptycho.py, tests/test_tomo.py
In this PR, I apply the multi-GPU ptychography design to tike. This new PR allows uneven partitioning of the input data.
Using multi-GPU requires manually spliting&destributing data to devices, creating multiple threads, and binding devices. Since `nscan` parameter is removed, it can now conduct uneven partitioning for the input data. 
Accordingly, each data (e.g., `psi`) becomes a _list_ of `cupy.ndarray`. The size of each _list_ equal to the number of GPU devices. The splitting and distributing happen at `src/tike/ptycho/ptycho.py` and the operators are in `src/tike/operators/cupy/operator.py`.
Our hybrid parallelization model is applied at `src/tike/opt.py`. I apply gather-scatter mode to `dir` computing and all-reduce mode to `line-search` computing.
Creating multiple threads and …
=> NEW: Add multi-GPU feature to tike ptychography

src/tike/operators/cupy/lamino.py, src/tike/operators/cupy/usfft.cu, src/tike/operators/numpy/usfft.py
Reduce the memory footprint of USFFT operations. Closes #66 
Padding and unpadding operations in the usfft were using "wrap" mode that were associated with the scatter gather operations. These padding operations were equivalent to using modular arithmetic to wrap the indices of these operations. By using special indexing instead of padding and unpadding we remove additional memory usage that would grow with the desired accuracy of the transform.
Benchmark with the Laminography adjoint operator test: `n=224, ntheta=224, tilt=np.pi/3` where "used memory" is the volume of all arrays allocated during the test and "aquired memory" is the maximum size of the memory pool at any time.
Before:
| eps | used memory | acquired memory |
| - | - | - |
1e-2 | 8.70GB | 3.40GB
1e-4 | 8.78GB | 4.95GB
1e-6 …
=> REF: Remove padding and upadding operations from usfft

azure-pipelines.yml
Colleagues have convinced me that `tike` should require an NVidia GPU because the value added from being able to run tests without a GPU is not worth the maintenance overhead and confusion(?) caused by supporting two types of operators. Since, the project now has CI with GPU available, the excuse that we need to test without GPU is also no longer valid.
This PR sets up the CI with GPUs available.
=> MAI: Setup CI with GPU available

src/tike/operators/cupy/ptycho.py, src/tike/opt.py, src/tike/ptycho/solvers/combined.py, tests/test_ptycho.py
Decrease the time spend line searching with minimal effort. Related to #61, #60 .
Adjusted the initial step sizes for the ptychography solver according to my observations from two real datasets. While the probe step size seems to remain on the order of 1, the object step size consistently shrinks to the order of 1e-5. I guessed that this was related the scan area.
My observation is that applying the smaller initial step for the object update decreases times per epoch by an order of magnitude.
=> REF: Change initial step sizes for line search

src/tike/pool.py, src/tike/ptycho/ptycho.py
This PR fixes a bug where you cannot set the GPU using `with cupy.cuda.Device()`. The ability to set the GPU for using a single GPU was broken when I merged the single and multi-gpu code paths.
The ThreadPool class now internally tracks the IDs of the GPUs to be used and when the number of GPUs is set to 1, but the ids are not specified it pulls the current CUDA device through the CuPy API.
With this PR, the ThreadPool class supports setting arbitrary GPUs. However, you cannot set arbitrary GPUs because other portions of the code still have the GPU indexes hardcoded. For example, setting `num_gpu=(0, 1, 2, 3)` is equivalent to `num_gpu=4`. `num_gpu=(4, 5, 6, 7)` should be valid, but because of some hardcoding it will not work.
=> BUG: Run ptycho.reconstruct on single device with id > 0

src/tike/ptycho/ptycho.py
Recent versions of numpy/cupy do not cast complex values to floats
with the square() even though the imaginary part is always zero.
This patch drops the imaginary part before returning from simulate.
=> BUG: Return floating type from ptycho.simulate()

azure-pipelines.yml
I noticed that sometimes the install step resolves to the wrong python version. These changes should ensure that all packages are resolved under the constraint of the desired python version.
=> CI: Ensure builds on correct python version

src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/__init__.py, tests/test_ptycho.py
The check for invalid algorithm names fails when the algorithm
name matches any object in the solvers namespace. The solution
for this is the check against the contents of an explicitly set
`__all__` parameter which will only ever contain the names of
valid solver functions.
Previously dir(solvers) was used in order to automate the
generation of this list. However, it seems that this is unsafe.
=> BUG: Invalid algorithms not caught when matching submodule name

azure-pipelines.yml
Fixing driver incompatibility on CI because cudatoolkit=11 was recently published to conda, but the CI still uses a container with cudatoolkit=10.
=> CI: Ensure that cudatoolkit matches agent cudatoolkit

azure-pipelines.yml
CI was failing on the step to remove previous environment. Local tests show that this removal step isn't strictly necessary, we can just override an existing environment with `--yes`.
=> CI: Try to make CI more robust to file debris

src/tike/operators/cupy/propagation.py, src/tike/opt.py
Adjusts the line search and conjugate gradient functions with new tuning parameters and more verbose logging output by default. These features are useful for choosing the starting step size for conjugate gradient and will let the user know if the initial step size is too large.
I have also changed the cost functions to use a mean instead of sum. This allows comparing mini-batches of different sizes directly.
=> NEW: Add more options and logging to linesarch and conjugate_gradient

azure-pipelines.yml
Updated workers to automatically clean themselves, so it's not necessary to include in the build steps of the repositories.
=> CI: Do cleaning elsewhere

src/tike/opt.py, src/tike/ptycho/solvers/combined.py, src/tike/ptycho/solvers/divided.py
Because Python memory operators are not always in-place, we must update the array of eigen_weights with new values.
=> BUG: Reassign updated eigenprobe batches

src/tike/ptycho/io.py, src/tike/ptycho/ptycho.py
Implement a function to load data from the APS Velociprobe format.
Uses HDF5 and NumPy to load the diffraction patterns and other parameters from an HDF5 file and some preprocessed scanning positions from a CSV file.
From my tests of fly-scan data from 2019-2, it seems that often the number of scanning positions *does not match* the number of frame collected. Thus, I truncate the data to the shorter of the two lengths.
I tested multiple datasets from different runs: RAVEN_IC RAVEN_pillar, and XBIC and was able to see reconstructions.
=> NEW: Implement functions for loading Velociprobe raw data

src/tike/operators/cupy/usfft.py
The cupy.int() functionality is deprecated. I followed recommendations and cast to python built-in int instead.
=> BUG: Silence deprecation warning about type cast

requirements.txt, src/tike/__init__.py, src/tike/operators/cupy/bucket.py, src/tike/operators/cupy/flow.py, src/tike/operators/cupy/lamino.py, src/tike/operators/cupy/patch.py, src/tike/operators/cupy/usfft.py
pkg_resources from setuptools is deprecated. Moving uses to importlib using backport libraries for pythons<3.8.
Using importlib to replace pkg_resources as recommended by setuptools docs.
=> REF: Replace deprecated pkg_resources with importlib

docs/source/api/ptycho.solvers.rst, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/__init__.py, src/tike/ptycho/solvers/adam.py, src/tike/ptycho/solvers/conjugate.py, src/tike/ptycho/solvers/epie.py, src/tike/ptycho/solvers/lstsq.py, tests/test_ptycho.py
Before refactoring the tike.ptycho.reconstruct API and related functions, I thought it would be good to clean-up and harden the tike.ptycho.solvers API. This serves the purpose of allowing parallel works on the internals of the solvers and the setup/teardown machinery that manages these solvers with less mystery about whether something will break.
Removed parameters from functions in ptycho.solvers that are unused. This also means that each function should not longer be passed any parameters that it doesn't use.
Add documentation strings that explain all of the parameters.
@stevehenke, I only filled out the docstrings for the ptycho.solvers.lstsq_grad method. If they seem understandable, then I will copy them to the other functions in the module.
=> API: Remove unused parameters from ptycho.solvers

azure-pipelines.yml, src/tike/communicators/pool.py, src/tike/operators/cupy/__init__.py, src/tike/operators/cupy/cache.py, src/tike/operators/cupy/lamino.py, src/tike/operators/cupy/propagation.py, src/tike/operators/cupy/shift.py, tests/print-gpu-info.py
Fixes two sources of error only observed in multi-GPU mode. 1. memory was being copied to the host from the gpu without setting the correct device context. 2. FFT plan cache was being used without setting the correct device context.
=> BUG: Fix illegal memory access errors

azure-pipelines.yml, src/tike/operators/cupy/convolution.py, src/tike/operators/cupy/ptycho.py, src/tike/ptycho/solvers/divided.py, src/tike/ptycho/solvers/epie.py, src/tike/view.py, tests/operators/test_convolution.py, tests/operators/test_ptycho.py, tests/operators/util.py, tests/test_ptycho.py
We can save a few FFTs by computing the adjoint for the object and probe simultaneously. This PR implements that functionality. Also, suspiciously the operators module is looking very similar to the Pytorch framework.
Implemented the adjoint operator for Ptycho that does both probe and object at the same time. Positions are still assume to be constant though. Also dropped in the Ptycho forward operation into epie and lstsq_grad where there was some old code from before Ptycho could handle multiple probes simultaneously.
=> NEW: Perform ptycho adjoints for probe and obj simultaneously

src/tike/ptycho/probe.py, src/tike/ptycho/solvers/lstsq.py, tests/test_ptycho.py
This PR pulls in changes from one of my personal development branches to fix a bug where cupy arrays are indexed outside of their proper device context. It does this by refactoring the eigen probe updates so they use our special CUDA context `map()` instead of a list comprehension.
=> BUG: Must index eigen probes in correct device context

src/tike/ptycho/solvers/options.py
An addendum to #182, that I forgot to push before merging.
=> BUG: Hide costs/times from IterativeOptions constructor

src/tike/operators/cupy/cache.py, src/tike/operators/cupy/lamino.py, src/tike/operators/cupy/propagation.py, src/tike/operators/cupy/shift.py, src/tike/ptycho/position.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py
Fixes #187. Because we use a modified ThreadPool.map() to ensure that CuPy arrays are always operated on in the correct device context, the automatic FFT plan cache from CuPy does not work correctly. This is because the cache is not (cannot be?) cleared automatically when the thread pool is destroyed because the threads don't know when they will be destroyed, so it exists beyond the life of the threads in the ThreadPool. This leads to a memory leak because if a new Comm object is created, then new threads create new FFT caches that are never destroyed. There is no way to disable the automatic cache globally (that I know of).
We solve this problem by reverting to our custom cache which only caches per device and is directly tied to the life of the Operator using the FFTs. This way, the …
=> Fix memory leak due to CuPy automatic FFT Cache

src/tike/ptycho/position.py, src/tike/ptycho/ptycho.py
Provide helpful feedback to programmers learning to use the tike.ptycho.reconstruct API.
Check (in earnest) all the main inputs of tike.ptycho.reconstruct for correct shapes and other geometric constraints.
=> API: Raise ValueError when ptycho input shapes are wrong

src/tike/ptycho/io.py, src/tike/ptycho/ptycho.py
Realized that the psi parameter is required, but has a default value of None. This is left over from a previous API breaking change where I removed auto-initialization of psi. This fix moves psi to the position parameters, so that the error raised tells the user that psi is required instead of that `None` has no parameters.
Also, adds a parameter to the velociprobe data loader, so that the data cropping can be controlled by the user.
=> API: Make psi parameter of tike.ptycho.reconstruct positional

src/tike/ptycho/solvers/lstsq.py
Fixes some implementation differences in the lstsq_grad method that cause less good performance of this algorithm. These differences include using the farplane gradient directly in the nearplane updates, adding some tiny constants to prevent instability, and only using real values for the optimal steps.
=> Fix some implementation differences in lstsq_grad method

src/tike/ptycho/object.py, src/tike/ptycho/probe.py, src/tike/ptycho/ptycho.py, tests/ptycho/test_probe.py, tests/ptycho/test_ptycho.py
This constrains the probe power ambiguity where the probe can
increase in power and have an equivalent solution.
Prevent power creep and ambiguity in the object and probe multiplication by force clipping the object magnitude to less than or equal to 1.
I also tried dividing the object and multiplying the probe by the maximum object magnitude each epoch, but this approach did not work well because it caused the ADAM algorithm to diverge.
=> NEW: Hard theshold ptycho object magnitude to <= 1.0

src/tike/linalg.py, src/tike/ptycho/probe.py, src/tike/ptycho/solvers/lstsq.py
Adding some assertions showed that the probe orthogonalization
for variable probes was not correct because the resulting probes
were not sorted by power from most to least.
A new parameter for the orthogonalize_gs method allows the
correct probe orthogonalization for these probes and a sorting step is added to sort the probes by their power.
=> BUG: constrain variable probes orthogonal

src/tike/ptycho/ptycho.py
On two occasions users experienced NaN reconstructions because
diffraction data contained negative values. Hours of debugging may
be prevented if users are warned of this hard to diagnose problem.
Warn users about improper data that may cause bad reconstructions.
Check all incoming diffraction patterns for non-finite and negative values.
=> DOC: Add user warning for invalid diffraction pattern values

azure-pipelines.yml, src/tike/communicators/pool.py, src/tike/ptycho/io.py, src/tike/ptycho/object.py, src/tike/ptycho/probe.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/options.py, tests/operators/test_lamino.py, tests/operators/util.py, tests/ptycho/test_position.py, tests/ptycho/test_probe.py, tests/ptycho/test_ptycho.py, tests/test_comm.py, tests/test_lamino.py, tests/test_opt.py, tests/test_pool.py
Check that ptychography reconstruction are working properly with multiple MPI ranks.
Ran the ptychography tests on MONA with 2 MPI ranks and 4 devices per rank. Uncovered a bug in the MPI code paths when multiple ranks run on the same node.
MPI tests now automatically divide devices on a single node amongst the the ranks instead of reusing the same devices.
=> TST: Refactor MPI enabled ptycho tests to not share devices

src/tike/operators/cupy/convolution.cu, src/tike/operators/cupy/convolution.py, src/tike/operators/cupy/patch.py, src/tike/ptycho/solvers/dm.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py, tests/operators/test_patch.py
Profiled some reconstructions and the patch adjoint kernel was the most time function. I tried to make that kernel faster, but I didn't really make any significant differences. This is just a result of some minor tweaks that I made along the way.
The main outcome of this tweaking was that I added an extra parameter to the kernel that allows for a new kind of broadcasting in order to avoid a memory copy in certain places in the code.
I used the CuPy wrapper API for NVProf to generate some timing reports:
```
Type  Time(%)      Time     Calls       Avg       Min       Max  Name
GPU activities:   29.26%  1.05751s      1600  660.94us  624.57us  1.0273ms  adj_patch
14.53%  525.20ms      4032  130.26us  1.2800us  760.16us  cupy_multiply__complex64_complex64_complex64
6.67%  240.99ms      1152 …
```
=> REF: Optimize patch adjoint operation

src/tike/cluster.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/options.py, src/tike/random.py, tests/ptycho/test_ptycho.py, tests/test_random.py
Collect all of the clustering methods into a single module. This is to prevent circular imports when trying to use these methods inside the ptychography module.
I have renamed and moved all of the clustering related functsion into the cluster module. I have dropped the leading words "split" and "cluster" because these are redundant when using the full names of the functions i.e. `tike.cluster.cluster_compact` vs `tike.cluster.compact`.
In order to prevent API breaks, I have added wrapper functions with deprecation warnings for the cluster functions which were in the public API. This includes the `batch_method` parameter in `PtychoParameters`.
=> REF: Move clustering methods to a single module

src/tike/ptycho/ptycho.py
By default, CuPy uses a memory pool instead of allocating a unique block of memory for every array created. This means that CuPy will continue to reserve GPU memory on a device even if all the CuPy arrays are destroyed. This causes a small reconstruction after a large reconstruction in the same script to use the same amount of memory.
Ask the memory pool to trim itself to the only actively used memory at the end of a reconstruction.
Users could also manually disable the memory pool [1], then I guess CuPy makes memory allocations that are tied to the life of each array.
[1] https://docs.cupy.dev/en/stable/user_guide/memory.html#memory-pool-operations
=> NEW: Trim memory pool at the end of reconstruction

src/tike/ptycho/ptycho.py, tests/ptycho/test_ptycho.py
Fix a runtime error where the wrong keyword is used for a parameter of the smoothness_constraint function.
Use 'a' instead of 'r'.
=> BUG: Fix wrong parameter name used to call smoothness_constraint

src/tike/ptycho/exitwave.py, src/tike/ptycho/object.py, src/tike/ptycho/position.py, src/tike/ptycho/probe.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/adam.py, src/tike/ptycho/solvers/options.py, src/tike/ptycho/solvers/rpie.py
Actually return a copy of the parameters classes when using the copy_to_device/copy_to_host functions. This prevents unexpected behavior when a parameter of one of these classes is modified in place.
Use a convergence metric that checks how much (absolutely) the object has changed since the last epoch.
Return a new instance of the Parameter classes from the copy_to functions instead of a reference to the original.
=> REF: Actually copy parameters / Update convergence metric

docs/source/api/operators.rst, src/tike/operators/cupy/propagation.py, src/tike/operators/cupy/ptycho.py, src/tike/ptycho/exitwave.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/adam.py, src/tike/ptycho/solvers/conjugate.py, src/tike/ptycho/solvers/dm.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py
This parameter is redudant with ExitwaveOptions noise_model.
In a recent PR, a new method for specifying the noise model was introduced via the `noise_model` parameter of the `ExitwaveOptions` class. This PR removes the previous method of choosing the noise model, so that there are not two methods.
=> API: Remove redundant `model` parameter

src/tike/ptycho/position.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py, tests/ptycho/test_position.py
Implement a guardrail for probe position updates. When the magnitude of x/y update is larger than
a user-specified value, clip the update to that value. 
1. Added `update_magnitude_limit` in `PositionOptions`. 
2. In `rpie._update_position`, clip values `step` if their magnitude is larger than `position_options.update_magnitude_limit`.
=> NEW: Allow enabling limits for probe position update magnitude

src/tike/communicators/stream.py
Prevent GPU memory from being allocated at import time on the 0th GPU.
Streams take GPU memory and may be unused if only non-GPU functions are used, so wait until functions are called to do initialization.
=> BUG: Don't initialize CUDA Streams at import time

src/tike/random.py, tests/test_linalg.py
Creating a randomization generator opens a CUDA context on the current device, but we don't want that because the default device might not be used.
Switch back to the functional API which creates a new random state generator on-demand for every function call? Even though this API is deprecated due to less good randomness.
=> API: Remove tike.random.randomizer_cp to prevent context on unused devices

src/tike/ptycho/probe.py, src/tike/ptycho/ptycho.py
This doesn't fix the underlying cause of these hot spots but this should cure the symptoms of the underlying disease for the time being
Sometimes we see these strange "hot spots" in the shared probe modes; we are still unsure of the underlying cause of these hot spots but use of a median filter seems to be effective of removing them when do occur. 
I introduce a function that simply takes the absolute value of the shared probe modes, and applies a median filter to each mode. The width of the median window is specified in the .toml file; alternatively we default to NOT using any median filtering.
=> NEW: Optional median filtering of probe "hot spots"

src/tike/operators/cupy/convolution.py, src/tike/operators/cupy/multislice.py, src/tike/operators/cupy/ptycho.py, src/tike/ptycho/solvers/dm.py, tests/operators/test_multislice.py, tests/operators/test_ptycho.py
Implement a correct adjoint operation for multi-slice propagation.
- Replace placeholder class with correctly implemented MultiSlice operator
- Adjoint function is double adjoint instead of separate for probe and object
- Remove *unused* specialized adjoint methods from the Ptycho operator because these methods would require reimplementation to work with the new MultiSlice operator
- Implement new operator tests for the new MultiSlice and Ptycho Operator APIs; these tests prove that the adjoint operations are correct
=> NEW: Implement multislice propagation operator with correct adjoint

src/tike/ptycho/probe.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py, tests/ptycho/test_probe.py
Organize the code and make algorithm implementation less complicated by moving the probe constraints all to one section.
Convert the additional probe penalty and finite support probe constraints to the probe constraint section, and implement them as soft constraints.
Adjust the constrain center peak function to only take single pixel steps. This prevents large and sudden movements of the probe function in order to keep it centered. The method for determining the center is now also center of mass instead of finding the brightest spot.
=> API: Move finite support probe constraints to probe constraints section

src/tike/ptycho/object.py, src/tike/ptycho/position.py, src/tike/ptycho/probe.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py, tests/ptycho/test_position.py, tests/test_random.py
Avoid deprecation warnings and fix errors from NumPy 2.0 API.
Ran the tests and fixed errors and deprecation warnings related to type casting from complex to real and from Python types to NumPy types.
=> BUG: Fix errors from deprecated API use with NumPy 2.0 API

src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/lstsq.py, src/tike/ptycho/solvers/rpie.py
Try to avoid host synchronization during cost function computation.
Store objective function values in an GPU array until the end of the epoch.
=> REF: Change how costs are reduced

src/tike/operators/cupy/fresnelspectprop.py, src/tike/operators/cupy/multislice.py, src/tike/operators/cupy/ptycho.py, src/tike/ptycho/object.py, src/tike/ptycho/probe.py, src/tike/ptycho/ptycho.py, tests/operators/test_multislice.py
Previously the multislice class and resulting forward and adjoint operators didn't use the specified parameters (e.g. probe wavelength, probe field of view (FOV), and multislice propagation distance), and instead always used the defaults.
Now, these parameters are explicitly passed into the multislice class.
Also, I now use the same propagator that fold_slice uses, not the one without phase prefactors and with the square root taylor expansion.
The probe wavelength and probe field of view (FOV) are now part of probe_options and multislice propagation distance is part of object options.
These parameters are then used in the multislice class for a composite operator which uses fresnel spectrum propagation of the  type fold_slice uses.
=> probe options and object options now include relevant Fresnel spectrum propagation multislice parameters and are used in the fwd and adj operators

src/tike/operators/cupy/fresnelspectprop.py, src/tike/operators/cupy/multislice.py, src/tike/operators/cupy/ptycho.py, src/tike/ptycho/ptycho.py, src/tike/ptycho/solvers/_preconditioner.py, src/tike/ptycho/solvers/rpie.py
After extensive testing on various benchmarking datasets (experimental and simulated), I believe multislice rPIE is ready to be merged into the main branch of TIKE.
The preconditioners are calculated for each slice in the sample, and these are then used in the sample update for each slice in a 3PIE style of update and the probe is updated using only the first slice of the sample and probe...this is a similar scheme that fold_slice uses in their LSTSQ multislice solver.
=> multislice rPIE ready for main branch after testing Daniel's reworkng of multiGPU workflow
