AdvancedPhotonSource/tike

- CMakeLists.txt
- azure-pipelines.yml
- docs/pull_requst_template.md
- meta.yaml
- setup.cfg
- src/CMakeLists.txt
- src/tike/__init__.py
- src/tike/communicator.py
- src/tike/constants.py
- src/tike/coverage.py
- src/tike/libtike.py
- src/tike/libtikepy.py
- src/tike/ptycho.py
- src/tike/scan.py
- src/tike/tike.py
- src/tike/tomo.py
- src/tike/trajectory.py
- src/tike/utils.py
- src/tike/view.py
I have reformatted all of the code using YAPF, a PEP8 formatting tool for python. This tool will keep the style of the codebase consistent with less human effort. I have also added this new pull request template in order to make pull requests more structured.
Configuring YAPF required adding some text to `setup.cfg`. The pull request template is a markdown file located in `/docs`.
No tests are required because these are not functional changes to the code.
> STY: Reformat code using YAPF and add pull request template

- src/tike/scan.py
- src/tike/view.py
I've implemented a function which will provide the positions on a hexagonal grid.
Hexagonal grid positions are generated row-by-row. Each row is `h = sqrt(3) / 2 * D` units apart because hexagonal packing. A square function which oscillates back and forth is used to make each row fit the previous row.
> Hexagonal step scans

- .readthedocs.yml
- azure-pipelines.yml
- docs/INSTALL.rst
- docs/requirements.txt
- docs/source/api-class-diagram.mmd
- docs/source/api-class-diagram.svg
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
Just setting up readthedocs for this repository
> DOC: Add RTD config file

- src/tike/ptycho/probe.py
Provide some Python probe initialization and orthogonalization routines that the Swiss are using in their MATLAB code.
> NEW: Add some probe initialization and orthogonalization tools

- src/tike/ptycho/probe.py
Fixes a bug in add_modes_random_phase in which
additional modes were ones shifted instead of the first mode shifted.
> BUG: Additional modes are ones phase shifted

- MANIFEST.in
- src/tike/operators/__init__.py
The purpose of these fixes it to make installation more reliable and easier to debug.
> Fix some setup and import things 

- src/tike/operators/cupy/propagation.py
> DEV: Remove TODO about checking cupy==7.4

- src/tike/operators/numpy/ptycho.py
Updating some parameter shape documentation for @xiaodong-yu.
> Update parameter shapes in Ptycho docs

- src/tike/operators/cupy/lamino.py
- src/tike/operators/numpy/lamino.py
- src/tike/operators/numpy/usfft.py
- tests/operators/test_checkerboard.py
This pull request addresses #66. Basically, the memory footprint of the Lamino operator is too large.
There are two approaches used in this pull request.
First, the checkerboard method for FFT shifting is implemented. This method uses properties of the FFT such that multiplying an array with a checkerboard of -1, 1 before and after the FFT is applied is equivalent to performing an FFT shift before and after.
Second, I dropped in the CuPy FFT functions that allow for the `overwrite_x` parameter which enables in-place FFT operations if available.
These two approaches have reduced the memory consumption of the Lamino operator by approximately half. Here is the memory usage before the changes:
```
tests/operators/test_lamino.py:49:test_adjoint (9.37GB, 5.57GB) …
```
> Reduce memory footprint of Lamino and USFFT

- meta.yaml
- requirements.txt
- src/tike/align/align.py
- src/tike/align/solvers/__init__.py
- src/tike/align/solvers/farneback.py
- src/tike/operators/__init__.py
- src/tike/operators/numpy/__init__.py
- src/tike/operators/numpy/flow.py
- tests/operators/test_flow.py
- tests/test_align.py
This PR is supposed to introduce the Flow operator and wrap Farnebacks flow solver from OpenCV, but I am having trouble getting Farnebacks method to work for simple uniform shifts!
**UPDATE:**
I discovered that the OpenCV implementation is sensitive to receiving view of arrays. So instead of accepting any shaped inputs, the Farneback alignment method can only do 3D arrays. I created some tests for the flow operator and Farneback method. The Flow operator's inverse is only adjoint for integer shifts. This may be due to interpolation errors.
> Implementing Flow operator

- setup.py
- src/tike/operators/__init__.py
Make operator module selection simpler and to allow different operator implementations to be incomplete,
The entry point for operators now points to the module itself instead of having a separate entry point for each Operator.
An import Warning is raised for each Operator that is not implemented.
> API: Refactor operator module selection

- src/tike/pool.py
- src/tike/ptycho/ptycho.py
- tests/test_pool.py
Squash a bug where the tests fail due to there not being enough GPUs because the tests always test the multi-gpu code path (maybe that's fine?).
The Pool class now limits the number of workers to the number of available GPUs and emits a warning.
> BUG: Test fail with one GPU because of multi-device

- azure-pipelines.yml
- meta.yaml
- src/tike/operators/__init__.py
- src/tike/operators/cupy/__init__.py
- src/tike/operators/cupy/flow.py
- src/tike/operators/numpy/flow.py
- tests/test_align.py
Allow CuPy backend with align module by implementing the Flow operator.
Switch to Lanczos interpolation for Flow operator because map_coordinates for CuPy only has 1st order spline interpolation.
> NEW: Implement Flow operator for CuPy

- src/tike/operators/cupy/convolution.cu
- src/tike/operators/cupy/convolution.py
Partially addresses #81 by refactoring the Convolution Operator CUDA kernel.
Replaces an if/else statement with functions and tunes the launch parameters. However, in my tests, I saw no significant difference in kernel run time.
> Refactor convolution kernel

- src/tike/ptycho/ptycho.py
This commit patches a bug which was introduced when I implemented randomized mini-batches. The problem is that when creating the random mini-batches, the scan positions and data may be reordered, but only the scan positions are returned. This causes the scan positions and data to become out of sync. The solution to this problem is to resort the scan positions before returning them so that they are in the same order as the original provided data.
> BUG: Reorder scan positions to original order before returning

- src/tike/communicators/pool.py
- src/tike/lamino/lamino.py
- src/tike/lamino/solvers/cgrad.py
- src/tike/operators/cupy/lamino.py
- tests/operators/test_lamino.py
- tests/test_lamino.py
Add multi-device parallelism to the laminography solver.
Ported the same map reduce approach used in the ptycho cgrad solver.
> NEW: Add thread pool to lamino solver

- src/tike/opt.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/combined.py
- src/tike/ptycho/solvers/divided.py
Make unique minibatches each epoch instead of using the same minibatches each epoch.
Move minibatch selection into solvers so that indexing is used to select the minibatches each epoch instead of separating minibatches into a list when the data is pushed to the GPU(s).
No new functionality that needs testing.
> REF: Move minibatch selection into solvers

- src/tike/lamino/lamino.py
- src/tike/lamino/solvers/cgrad.py
- tests/test_lamino.py
Heuristically provide an initial step size for the conjugate gradient steps that will automatically scale with problem size and other parameters. Previously, the initial step length for the backtracking line search was fixed to 1. This causes many backtracks or an insufficiently aggressive updates.
The initial step size is estimated to be  ` 2 * |F*Fm| / |m|` where `F` is the forward operator, `F*` is the adjoint operator, `m` are the inputs to the operator that will be updated by this step, and `||` signifies the complex L2 norm.
Initially, I was trying to make all of the operator in tike ['normalized' operators](https://en.wikipedia.org/wiki/Normal_operator), but 'normalized operators' adjoint and forward operators must span the same space. This means that operators like the radon …
> NEW: Provide initial guess for laminography step size using operator norms

- src/tike/ptycho/learn.py
- src/tike/ptycho/position.py
- src/tike/ptycho/ptycho.py
- tests/test_ptycho.py
Add a top-level function which extracts arbitrary patches from a reconstructed object function.
Wrap the Patch operator so that the function can be called with NumPy arrays.
No tests. I'm not sure they are needed because the Patch operator is tested by the tests of the Convolution and Ptycho operators.
> NEW: Patch extraction function for training neural nets

- src/tike/ptycho/io.py
To allow loading position data directly from raw position files. This will allow us to dynamically adjust how fly-scans are handled in the future by changing the new `position_reduce` function from this PR.
Copied the procedures from a Python script that Yi gave me. I tested this approach by comparing the output of the parsed files with the files produced by Yi's script and those that already exist in the fly145 folder on micdata.
> NEW: Load positions from raw velociprobe files

- src/tike/opt.py
Adds functions for generating the Adagrad (adaptive gradient) and AdaM (adaptive moment) directions. The functions help gradient descent algorithms converge by smoothing the search direction between iterations and taking larger steps in directions that are repeatedly used.
Wrote functions which accept the current gradient and return a new gradient plus additional metadata that need to be saved across iterations for each approach.
> NEW: Add gradient acceleration methods to tike.opt

- src/tike/operators/cupy/bucket.py
Fixes a problem where kernel functions are loaded to the wrong GPU.
See commit notes.
> BUG: Fix module loading on wrong device

- docs/source/api/ptycho.object.rst
- docs/source/api/ptycho.rst
- src/tike/ptycho/object.py
- src/tike/ptycho/solvers/combined.py
- src/tike/ptycho/solvers/divided.py
- tests/test_ptycho.py
Reduce the number of function arguments in ptychographic reconstruction methods.
Combine various arguments related to the object into "ObjectOptions" class. This allows for easier management of complicated parameters and setting/getting of default values.
Related to #15 Related to #147
> REF: Create ObjectOptions dataclass to store object options

- src/tike/lamino/lamino.py
- src/tike/operators/cupy/lamino.py
Just adding some more documentation to the public Lamino API.
> DOC: Add more information to Lamino docstrings

- src/tike/communicators/pool.py
- src/tike/ptycho/ptycho.py
Fix some GPU selection bugs which prevented proper behavior when choosing a set of non-sequential GPU ids.
i.e. choosing GPUs (1, 3, 5, 7) or (0, 5, 6, 7) would not work properly.
Ensuring that the proper device indices and device contexts are used in ptycho.reconstruct and comm.pool
> BUG: Fix/gpu indexing

- src/tike/communicators/comm.py
- src/tike/communicators/pool.py
- src/tike/lamino/lamino.py
- src/tike/operators/cupy/bucket.py
- src/tike/opt.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/combined.py
- src/tike/ptycho/solvers/divided.py
- tests/operators/test_lamino.py
- tests/test_comm.py
- tests/test_pool.py
- tests/test_ptycho.py
This PR contains the changes from #153 that are related to the ThreadPool and Bucket operator only. I want to merge these changes earlier than #153 because it contains changes which affect work on other branches.
> API: Add new grouped thread-pool operations and update Bucket

- tests/test_ptycho.py
Add more detailed information to unittest output regarding the reconstructed probes.
Save the probe intensity as a png for both shared and variable probes.
> TST: Save more detailed probe information

- src/tike/ptycho/ptycho.py
- src/tike/random.py
- tests/test_random.py
Adds tests which handle when the number of requested clusters is 1 or fewer and greater than the total population.
Realized while running unrelated tests that wobbly_center was not working for all valid cluster sizes. Added tests to check all of the edge cases, then updated the docs/source accordingly.
> BUG: Test and handle edge cases for wobbly_center

- src/tike/ptycho/probe.py
- src/tike/ptycho/solvers/__init__.py
- src/tike/ptycho/solvers/epie.py
- tests/test_ptycho.py
Implement the extended ptychographic iterative engine (ePIE) algorithm based on Maiden's 2009 paper.
Started with the lstsq_grad implementation because they are similar, but changed the update directions and gradients accordingly. There are a few significant differences between the paper and this implementation:
1. This implementation allows batches of more than one pattern to be processed simultaneously. In this case, the object/probe updates are averaged across all the positions in the batch.
2. This implementation allows for multi-probe illumination. In this case, the wavefront updates are based on the gradients of the Gaussian noise model as implemented in the other methods. Then the probes are updated in a simultaneous mode i.e. each mode uses the same object patches to compute its …
> NEW: Implement ePIE for ptychography

- src/tike/ptycho/ptycho.py
Refactors the setup/teardown code for ptychography reconstruction in order to make it more compact and more clearly separate from the reconstruction algorithm part.
Flattens the reconstruct function by removing some `if` blocks. Most of the removed `if` blocks are replaced with inline ternary operations.
Also added more documentation to the reconstruct funcition.
> REF: Reorganize ptycho.reconstruct setup/teardown

- src/tike/opt.py
- src/tike/ptycho/object.py
- src/tike/ptycho/position.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/solvers/adam.py
- tests/test_ptycho.py
Save some computation in ADAM algorithm by using full adjoint and simultaneous updates
> REF: Refactor ADAM to use full-adjoint

- src/tike/linalg.py
- src/tike/operators/cupy/patch.py
- src/tike/operators/cupy/propagation.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/solvers/lstsq.py
- tests/test_ptycho.py
Enables greater flexibility in varying probe components by allowing only some of the probes to have eigen components.
Added better documentation and changed the summation to construct varying probes.
> REF: Update varying probe setup function to allow more flexability

- azure-pipelines.yml
- docs/source/api/index.rst
- docs/source/api/random.rst
- src/tike/random.py
- tests/test_random.py
Related to #145. Implements an algorithm for compact batch selection.
Uses a modified k-means clustering algorithm which limits the cluster sizes to be approximately equal. Starts with [kmeans++](https://en.wikipedia.org/wiki/K-means%2B%2B) to initialize the clusters, then cycles through the points trying to swap them such that the total distance from point to cluster centroid is minimized. This swapping heuristic technically does not minimize the kmeans objective, but it does a good job of creating clusters without enclaves.
> NEW: Implement compact clustering methods for mini-batch selection

- src/tike/ptycho/ptycho.py
Reduce the number of required parameters for ptycho.reconstruct.
Set a default reconstruction algorithm.
> API: Set a default ptycho reconstruct algorithm

- src/tike/communicators/pool.py
- src/tike/ptycho/object.py
- src/tike/ptycho/position.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/rpie.py
- src/tike/view.py
- tests/test_ptycho.py
Add position correction feature to the RPIE implementation.
Copies the position correction implementation from the lstsq_grad algorithm. This approach approximates the position update direction using finite element on each object patch and then amplifies the update information from these patches across iterations using ADAM (Adaptive Moment).
> Port position correction to RPIE

- src/tike/ptycho/ptycho.py
Help users understand why they are running out of GPU memory.
Add a try-catch block around the first probably OutOfMemoryError and suggest increasing the number of batches which is the primary way to avoid running out of memory.
No tests needed because it's just documentation.
> DOC: Add context to first likely out of memory error

- azure-pipelines.yml
- requirements.txt
Patch the CI environment to avoid [a CuPy version which has a bug related to type conversion](https://github.com/cupy/cupy/issues/6615).
Add requirement that CuPy is not 10.3.0.
> CI: Avoid bug in CuPy version 10.3.0

- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
- tests/test_ptycho.py
Adds PIE-like preconditioner to lstsq_grad updates.
Divide the object gradient by a weighted average of the probe amplitude and the maximum probe amplitude.
> REF: Normalize lstsq_grad updates using total illumination

- src/tike/ptycho/io.py
Closes #197
Check the input data for values that will cause ptychography reconstructions to fail.
Adds user warnings in the io module data loader.
> NEW: Add data loading checks for nonfinite and negative values

- src/tike/linalg.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/options.py
- src/tike/view.py
- tests/ptycho/test_probe.py
- tests/ptycho/test_ptycho.py
Fix eigen probe and variable intensity updates with comparison from ptychoshelves.
> REF: Update lstsq variable probe updates

- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/options.py
- src/tike/random.py
Enable switching batch selection method from public API.
Adds a parameter to the algorithm options data class which lets the user choose which batch selection method to use.
> NEW: Allow switching batch selection methods

- src/tike/ptycho/solvers/lstsq.py
- tests/ptycho/test_ptycho.py
Add optional momentum acceleration to lstsq_grad object updates.
Computes the ADAM update from the lstsq_grad object update. Only adds ADAM to the object update and not the probe update because probe updates are unstable when accelerated.
> NEW: Add momentum acceleration to object only for lstsq method

- src/tike/ptycho/position.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
Refactor gradient position updates in lstsq and rPIE methods to improve stability.
Adds sets a minimum value for the update denominator to prevent division by zero.
Uses all probes instead of just the last probe for rPIE position update.
Use rPIE-like denominator for position update in lstsq method.
> REF: Update rPIE/lstsq_grad position correction

- src/tike/view.py
Closes #209
Add a function to plot relative probe power.
No tests for plotting functions.
> NEW: Add a function to plot probe power

- src/tike/ptycho/object.py
- tests/ptycho/test_ptycho.py
Closes #210
To provide an estimated absorption image from the diffraction patterns and scan positions.
First compute the total intensity of each diffraction pattern, then use these points to interpolate a gridded image. Use scipy's interpolation schemes.
> NEW: Add utility function to estimate absorption image

- src/tike/ptycho/io.py
- src/tike/ptycho/object.py
- src/tike/ptycho/ptycho.py
Experimental data is collected as uint12, so promoting to float32
is probably losing precision and increasing memory requirements.
Move diffraction data to GPU as uint16 instead of float32. Auto-promotion happens only the fly only when the data is used in evaluating a gradient or cost function.
> API: Store diffraction data as uint16 instead of float32

- src/tike/ptycho/ptycho.py
To make the error message more helpful.
> DOC: Make the probe/data shape message more helpful

- setup.cfg
- src/tike/communicators/comm.py
- src/tike/communicators/mpi.py
- src/tike/lamino/solvers/bucket.py
- tests/ptycho/test_ptycho.py
- tests/test_comm.py
- tests/test_lamino.py
If mpi4py is unimportable, then replace the MPIComm class with
None and skip all the MPI related tests.
@tekinbicer requested that MPI be an optional dependency because he found it to be burdensome when he wasn't using it. This PR makes it optional.
Hide imports of mpi4py behind try-except blocks. Catch the ModuleNotFoundError and set values that would have been set with placeholders.
> NEW: Make mpi an optional feature

- src/tike/ptycho/probe.py
- src/tike/ptycho/solvers/__init__.py
- src/tike/ptycho/solvers/adam.py
- src/tike/ptycho/solvers/conjugate.py
- src/tike/ptycho/solvers/dm.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/options.py
- src/tike/ptycho/solvers/rpie.py
- tests/ptycho/test_ptycho.py
Add an implementation of the Difference Map algorithm.
Adapted the current RPIE implementation for DM. The farplane updates are the same, but difference map has different nearplane updates. DM requires that all positions be used for each update, so I had to adapt the batch parameter so that only one update is applied each epoch.
> NEW: Implement Difference Map algorithm

- src/tike/ptycho/object.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/lstsq.py
- tests/ptycho/test_ptycho.py
Allow compact mini-batches with synchronized updates for the lstsq method.
Instead of having a new preconditioner for each minibatch, preserve it over multiple updates.
Collect the object updates from all minibatches and apply them all at once instead of sequentially.
The preconditioner is averaged with the previous iteration preconditioner to have a geometric mean type smoothing.
> NEW: Smooth preconditioner and compact set updates

- src/tike/opt.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/adam.py
- src/tike/ptycho/solvers/conjugate.py
- src/tike/ptycho/solvers/dm.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/options.py
- src/tike/ptycho/solvers/rpie.py
- src/tike/view.py
- tests/ptycho/test_ptycho.py
- tests/test_opt.py
Monitor the cost function for convergence to allow for early termination or other convergence related features.
Use numpy polyfit to compute the slope of the cost function across some window of the latest epochs. If the slope is no longer decreasing, then the algorithm has converged!
We use an average cost function value from all mini-batches if there is more than one. Also, the cost from all mini-batches is now reported in the algorithm_options.costs parameter.
> NEW: Monitor cost function for convergence

- src/tike/ptycho/io.py
Implements a LYNX instrument dataloader based on velociprobe loader
> NEW: Add Lynx dataloader

- .git_archival.txt
- pyproject.toml
> BLD: Use new scm git archive API

- src/tike/operators/cupy/convolution.cu
- tests/operators/test_patch.py
> NEW: Optimizations and correctness tests for patch extraction operation

- docs/INSTALL.rst
- docs/source/api/ptycho.rst
- docs/source/conf.py
- requirements.txt
- setup.cfg
- src/tike/ptycho/object.py
- src/tike/ptycho/position.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/__init__.py
- src/tike/ptycho/solvers/options.py
- src/tike/view.py
- tests/operators/test_patch.py
- tests/operators/test_rotate.py
- tests/operators/test_usfft.py
- tests/ptycho/test_multigrid.py
- tests/ptycho/test_probe.py
- tests/ptycho/test_ptycho.py
- tests/test_lamino.py
- tests/test_random.py
- tests/test_tomo.py
- tests/test_view.py
Add a user-friendly wrapper around ptycho.reconstruct that implements a simple multi-grid reconstruction.
Downsamples the ptychography problem by powers of 2 a requested number of times. Then performs the requested number of iterations at all levels. Each level provides the initial guess for the next higher-resolution level via upsampling. Parameters are upsampled using scipy.ndimage.zoom which uses spline interpolation. Used zoom because it was convenient, but also the splines provide smooth transition from low resolution to high.
Comparison of different re-gridding methods here:
https://anl.box.com/s/uwbh80n0vz37dmtjbbnsig53m53as0fr
> NEW: Simple Multi-grid reconstruction method

- azure-pipelines.yml
- src/tike/communicators/pool.py
- src/tike/opt.py
- src/tike/ptycho/io.py
- src/tike/ptycho/solvers/dm.py
- tests/ptycho/test_ptycho.py
Add some minor features and bug fixes that I found when writing a new example script for ptychography reconstruction.
These fixes are all adhoc. Please see the commit messages and view changes one commit at a time for details.
Adding adaptive moment to DM deserves more explanation. Since DM does not have a conventional gradient based update, I added momentum by computing the update direction manually with a diff between the current and previous state of the variable. This allows tracking of a boosting directions that are updated more often.
> BUG: NEW: Some minor changes

- src/tike/ptycho/solvers/rpie.py
Make the use_adapative_moment option actually do something for rPIE
Optionally apply the momentum transformation to RPIE object update direction.
> NEW: Add momentum to rpie object update

- src/tike/ptycho/ptycho.py
Because:
- Reduces the number of synchronization calls between devices
- Allocates memory directly on GPU instead of transferring these two scalars from the host
- Reduces number of return parameters to simplify map syntax
> REF: Use device array instead of two scalars for rescale_probe

- src/tike/ptycho/object.py
- src/tike/ptycho/position.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/options.py
- src/tike/ptycho/solvers/rpie.py
Add an optional penalty that penalizes energy in higher order probes this penalty causes the energy to concentrate in the lower order modes (having fewer modes is better) instead of distributing evenly across all modes.
Add a penalty to the cost function for non-zero values in the probe matricies. The penalty increases linearly from 0 in the first mode to `b` in the final mode.
> NEW: Add penalty for higher modes existing

- src/tike/ptycho/position.py
- src/tike/ptycho/solvers/rpie.py
Fix a big copypasta error that caused momentum updates for position correction to be incorrect. Because of this bug, both the y components of the position updates used the x momentum instead of its own.
Use the correct setter syntax on the PositionOptions class.
> BUG: Remove copypasta setting of wrong momentum for position updates

- src/tike/ptycho/position.py
- src/tike/ptycho/solvers/dm.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
Update position update gradients with better gradient approximations.
Replace the ptychoshelves inspired FFT-based gradients with gradients based on finite-difference approximation. Just use the np.gradient function because it is easy. Also, considered Sobel operator, but this one had better scaling? Should do a performance comparison in the future.
> NEW: Use better image gradient for position updates

- src/tike/ptycho/position.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
- tests/compare_gradients.py
Use Gaussian derivatives instead of finite differences for position image update gradients.
> API: Use Guassian derivative image gradients

- src/tike/ptycho/solvers/lstsq.py
The final remaining compact clustering change. Closes #145
> NEW: Scale down probe updates for compact clustering

- tests/ptycho/__init__.py
- tests/ptycho/io.py
- tests/ptycho/templates.py
- tests/ptycho/test_multigrid.py
- tests/ptycho/test_online.py
- tests/ptycho/test_position.py
- tests/ptycho/test_probe.py
- tests/ptycho/test_ptycho.py
Shorten ptychography reconstruction test files.
Break the ptycho reconstruction tests into reusable components and distribute them across multiple topic-focused files.
> TST: Refactor reconstruction tests into smaller modules

- .github/workflows/unit-tests.yml
- src/tike/communicators/pool.py
- src/tike/lamino/bucket.py
I accidentally merged a debugging code change which disabled the ThreadPool map and replaced it with non-asynchronous map.
Re-enable asynchronous map, and fix a broken test.
> BUG: Fix disabled threadpool

- src/tike/communicators/comm.py
- src/tike/communicators/pool.py
- src/tike/linalg.py
- src/tike/operators/cupy/cache.py
- src/tike/operators/cupy/patch.py
- src/tike/operators/cupy/propagation.py
- src/tike/operators/cupy/ptycho.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/options.py
Avoid an API break in CuPy by using the numpy typing system directly. Cupy's typing module is basically an alias for NumPy's module, but non-public changes have broken compatability.
> REF: Add type hints to some modules

- src/tike/operators/cupy/cache.py
- src/tike/operators/cupy/patch.py
- src/tike/ptycho/ptycho.py
- tests/ptycho/io.py
- tests/ptycho/test_ptycho.py
Squashes some bugs and modifies some tests in response to debugging some reconstruction comparisons with Junjing.
> BUG: Some bug fixes and test changes

- src/tike/cluster.py
- src/tike/opt.py
- src/tike/view.py
- tests/ptycho/io.py
- tests/test_opt.py
This PR backports some unrelated changes from a long running branch that I have been working on.
> NEW: Assorted upgrades

- .github/workflows/unit-tests.yml
- docs/requirements.txt
- src/tike/ptycho/position.py
Provide ASCII art and text to explain how the tike coordinate system and edge padding work for ptychography.
> DOC: Add texplanation for the tike.ptycho coordinate system

- .github/workflows/unit-tests.yml
- pyproject.toml
- requirements.txt
- src/tike/communicators/pool.py
- src/tike/ptycho/object.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/adam.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
- src/tike/view.py
- tests/communicators/test_pool.py
- tests/ptycho/test_ptycho.py
Reimplement compact clustering methods for lstsq, adam, and rpie so that they use combined updates when using the compact clustering batch selection. Rpie and lstsq will also use a new convergence checked momentum.
Included in this PR is also an update of the minimum required python version to 3.8?
> REF: Cluster compact

- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/adam.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/options.py
- src/tike/ptycho/solvers/rpie.py
- src/tike/view.py
- tests/ptycho/io.py
- tests/ptycho/templates.py
- tests/ptycho/test_probe.py
Enable tracking of the evolution of the probe power across iterations.
Store the computation of probe power from orthogonalize_eig in the ProbeOptions struct. This allows plotting the probe power later after the reconstruction completes.
> NEW: Track evolving probe power

- src/tike/cluster.py
- tests/test_random.py
Fix a bug where compact clusters assertion failed when singleton clusters were generated on cluster initialization.
Properly remove full clusters from consideration.
> BUG: Allow for singleton clusters in compact cluster

- .github/workflows/unit-tests.yml
> CI: Pin the CUDA version because of driver on workers

- .gitignore
- src/tike/view.py
Prevent error from plotting Poisson cost function objectives.
Disable the log scale on the y-axis if any of the cost function values are non-positive.
> BUG: Disable log scale on plot_cost_convergence when negative

- src/tike/operators/cupy/__init__.py
- src/tike/operators/cupy/convolution.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/__init__.py
- src/tike/ptycho/solvers/_preconditioner.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
Centralize the computation of the preconditioner term which is used in both rPIE, DM, and lstsq methods.
Instead of computing the preconditioner inside each function at the start of or during iteration over the epoch, separate it into its own function which is called from the Reconstruction context iterate() method.
> REF: Shared preconditioner computation between algorithms

- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
> REF: Move constraints into general iteration loop

- src/tike/cluster.py
- src/tike/opt.py
- src/tike/ptycho/position.py
- src/tike/ptycho/solvers/adam.py
- src/tike/ptycho/solvers/conjugate.py
- src/tike/ptycho/solvers/dm.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
- tests/test_random.py
Provide a faster sparse clustering method than the wobbly center. The wobbly center algorithm is slow because it iterates over every member of the population.
Bootstrap the wobbly center clusters with random initialization which should be faster because it doesn't require looping over every point. Then use the wobbly center algorithm to determine cluster membership for the last few members.
> NEW: Hybrid Wobbly Center Random Clustering method

- src/tike/ptycho/ptycho.py
Duplicated args due to failed merge conflict resolution
> BUG: Duplicate arguments

- src/tike/lamino/solvers/bucket.py
- src/tike/lamino/solvers/cgrad.py
- src/tike/opt.py
- src/tike/ptycho/io.py
- src/tike/ptycho/position.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/dm.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
To make logging less verbose
Reduce the calls to the logging module to once per epoch or change the statement to a higher logging level
> DOC: Make logging less verbose

- src/tike/ptycho/solvers/lstsq.py
- tests/ptycho/io.py
- tests/ptycho/test_ptycho.py
Closes #280
Prevent runtime errors by adding branches to the code to handle the case when the probe is not updated for the lstsq method.
> BUG: Fix errors when probe updates disabled in lstsq method

- src/tike/ptycho/io.py
Allow pixel binning of detector pixels during data loading in ptycho.io functions
Add a binning step into the cropping and centering function.
> NEW: Enable pixel binning at load time for ptycho data

- .github/workflows/unit-tests.yml
- src/tike/operators/cupy/bucket.cu
- src/tike/operators/cupy/convolution.cu
- src/tike/operators/cupy/interp.cu
- src/tike/operators/cupy/usfft.cu
- tests/communicators/test_comm.py
- tests/communicators/test_mpi.py
- tests/operators/test_convolution.py
- tests/operators/test_ptycho.py
- tests/operators/util.py
- tests/ptycho/templates.py
> CI: Fix broken mpi4py removal step on CI

- src/tike/operators/cupy/ptycho.py
- src/tike/ptycho/solvers/_preconditioner.py
- tests/test_random.py
Use CuPy fuse to merge more function calls into single kernels which reduces the use of intermediate memory arrays and the number of kernel launches.
On a benchmarking dataset, the memory profile starts with 15.29GB of GPU memory acquired. After this PR, only 13.88GB of memory acquired.
> NEW: Use CuPy fuse to merge some reduction kernels

- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/options.py
Allow users to use wall time as a termination criteria.
Check what the cumulative reconstruction time is at the beginning of every epoch and return if it exceeds the number of seconds provided by the user.
> NEW: Stop reconstruction based on wall-time

- src/tike/communicators/stream.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/_preconditioner.py
- src/tike/ptycho/solvers/dm.py
- tests/communicators/test_streams.py
- tests/ptycho/test_online.py
Overlap computation and memory transfer better.
Use contiguous pinned memory and CUDA events to utilize streams more efficiently by writing a new stream_and_modify function.
> NEW: Start migration to new CUDA stream API

- src/tike/communicators/comm.py
- src/tike/communicators/mpi.py
Removes unneeded host to device transfer.
This transfer is redundant because we have a `check_opal` decorator which automatically does the host-device transfer if OPAL is not enabled.
> BUG: Remove unneeded device to host transfer

- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
- tests/ptycho/test_probe.py
Port the RPIE and LSTSQ implementations to the new CUDA Stream managing API. The one that requires contiguous GPU memory layout for batches and uses CUDA Events to coordinate memory transfers.
The variable probe update functions are made more explicit, and batch indexes are replaced with lo:hi ranges.
> REF: Migrate RPIE and LSTSQ methods to new Stream manager

- src/tike/operators/cupy/propagation.py
- src/tike/operators/cupy/ptycho.py
- src/tike/ptycho/exitwave.py
- src/tike/ptycho/probe.py
- src/tike/ptycho/ptycho.py
Allow to the user to choose a different scaling for the FFT operation in the ptychography forward operator. This will cause the probe to converge to a different magnitude depending on which scaling the user picks.
Mostly just passed through the `norm` option from the FFT function. In my tests, there doesn't seem to be a qualitative difference between the test reconstructions for each of the three normalization options. In order of smallest probe magnitude to largest, the options are 'backward', 'ortho', 'forward'.
The default scaling option is 'ortho' because that one is correct for the adjoint operation tests and it is the current behavior. Which every option keeps the probe magnitude small is technically the most "precise" because floating point numbers are more precise nearer zero.
> NEW: Expose FFT Scaling option

- src/tike/ptycho/position.py
- src/tike/view.py
Add a function to visualize AffineTransform for the purpose of comparing the transform between datasets/reconstruction parameters
Fix a bug where the PositionOptions is deleted when PtychoParameters are resampled.
The plotting function draws a unit circle transformed by the AffineTransform. Here is an example of what is drawn.
> NEW/BUG: Function to visualize AffineTransform

- src/tike/ptycho/solvers/options.py
- src/tike/view.py
Fix some syntax that is incompatible with older python versions.
Using typing.Optional and typing.Union instead of |
> BUG: Use syntax compatible with python 3.9/3.8

- pyproject.toml
- requirements.txt
https://github.com/cupy/cupy/issues/8184
Avoid a version of CuPy that doesn't work with sm < 7.0 because a header was added to the C code that won't JIT compile for sm < 7.0.
Add != expression to package requirements for CuPy.
> BLD: Skip cupy 13.0 due to broken ReductionKernel for sm<7

- src/tike/operators/cupy/convolution.py
- src/tike/operators/cupy/shift.py
- src/tike/ptycho/position.py
- src/tike/ptycho/ptycho.py
- src/tike/ptycho/solvers/dm.py
- src/tike/ptycho/solvers/lstsq.py
- src/tike/ptycho/solvers/rpie.py
- tests/operators/test_convolution.py
- tests/ptycho/test_position.py
Mitigate position correction slowly moving the object out of the field of view.
Use only the center half of the object patches to compute the position update directions. This avoids noise around the edges where information is less dense.
Subtract the mean position update direction using trim_mean before each update. This in theory should keep the object centered by preventing net movement. In practice, there is still a small amount of movement each epoch.
> NEW: Mitigate scan position global drift

- src/tike/ptycho/position.py
- src/tike/ptycho/solvers/lstsq.py
Use a fixed weighting for position correction regularization.
Since our estimation of the affine position matrix is already robust to outliers, we don't need to re-estimate which positions are outliers when applying regularization. So we just choose a 1:9 fixed ratio of position update from the individual position and the global position change.
> NEW: Use fixed confidence for position regularization

- .github/workflows/apptainer.yml
- apptainer/tike.def
- requirements-container.txt
> NEW: inject extra dependencies into the container release

- src/tike/ptycho/position.py
- src/tike/ptycho/ptycho.py
Notify the user if a global scaling is detected, so they can adjust their detector distance / beam energy accordingly.
> NEW: Add affine transformation to INFO logging output

- src/tike/ptycho/ptycho.py
> DOC: Add full affine transform to output logs

- src/tike/ptycho/solvers/lstsq.py
- tests/ptycho/test_ptycho.py
> REF: Reeenable probe support for lstsq_grad method

- src/tike/operators/cupy/multislice.py
- src/tike/operators/cupy/ptycho.py
- src/tike/ptycho/solvers/_preconditioner.py
- tests/operators/test_multislice.py
- tests/ptycho/templates.py
- Remove initialization parameter for nslices from operators
- Add test dataset for multislice reconstruction
- Compute object preconditioner for every slice instead of just first slice
> REF: Get number of slices dynamically at runtime

- src/tike/ptycho/position.py
- src/tike/ptycho/ptycho.py
> REL: Backport affine transform logging

- src/tike/ptycho/solvers/lstsq.py
Remove extra function definitions that were required when the lstsq method needed to synchronize between multiple GPUs during a single epoch. i.e. the flow of the algorithm needed to be broken up so that GPUs could trade information, but since that is no longer the case, it is not necessary to break the flow into smaller functions.
Merge functions which are called sequentially and/or have redundant reductions separating them.
> REF: Merge functions that are no longer separated by reduction
